apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nodejs-kubernetes-mongodb
  name: nodejs-kubernetes-mongodb
  namespace: node-mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs-kubernetes-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: nodejs-kubernetes-mongodb
    spec:
      containers:
        - env:
            - name: MONGO_DATA_DIR
              value: /data/db
            - name: MONGO_LOG_DIR
              value: /dev/null
          image: docker.io/mongo:4.2
          name: nodejs-kubernetes-mongodb
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: nodejs-kubernetes-mongodb-volume
      restartPolicy: Always
      volumes:
        - name: nodejs-kubernetes-mongodb-volume
          persistentVolumeClaim:
            claimName: nodejs-kubernetes-mongodb-volume

